// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Lclb.Cllb.Interfaces.GeoCoder
{
    using Microsoft.Rest;
    using Newtonsoft.Json;

    /// <summary>
    /// This API represents address cleaning, correction, completion,
    /// geocoding, reverse geocoding, and proximity resources for intersection
    /// addresses, physical addresses and their occupants in British Columbia.
    /// Please read our [data collection
    /// notice](https://github.com/bcgov/api-specs/blob/master/COLLECTION_NOTICE.md#collection-notice).
    ///
    /// Please note that you may experience issues when submitting requests to
    /// the delivery or test environment if using this [OpenAPI
    /// specification](https://github.com/bcgov/api-specs) in other API console
    /// viewers.
    ///
    /// [Developer API
    /// keys](https://github.com/bcgov/gwa/wiki/Developer-Guide#developer-api-keys)
    /// are unique and provide the ability to make up to 2 requests per second.
    /// Production government applications may use organization API keys which
    /// are further described in [the Developer
    /// guide](https://github.com/bcgov/gwa/wiki/Developer-Guide#developer-api-keys).
    ///
    /// **Notification: If you have applications or web pages that link to the
    /// public geocoder at one of the following URLs, please note that they are
    /// now deprecated [More
    /// Details](https://www2.gov.bc.ca/gov/content?id=103ADC5A956842828554238DEF28D6E5).
    /// - http://apps.gov.bc.ca/pub/geocoder
    /// - https://apps.gov.bc.ca/pub/geocoder
    ///
    ///
    /// **To acquire an API key please visit the [API Key
    /// Request](https://kq.apps.gov.bc.ca/) application.**
    ///
    /// </summary>
    public partial interface IGeocoderClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IGeoCoderAPI.
        /// </summary>
        IGeoCoderAPI GeoCoderAPI { get; }

    }
}
