apiVersion: v1
kind: Service
metadata:
  name: {{ include "cllc-web.fullname" . }}
spec:
  selector: {{- include "cllc-web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
