// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Gov.Lclb.Cllb.Public.Controllers.EstablishmentsController.GetMap(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Gov.Lclb.Cllb.Public.Controllers.EstablishmentsController.CreateEstablishment(Gov.Lclb.Cllb.Public.ViewModels.Establishment)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Gov.Lclb.Cllb.Public.Controllers.EstablishmentsController.GetMap(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Gov.Lclb.Cllb.Public.Controllers.EstablishmentsController.GetMap(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:Gov.Lclb.Cllb.Public.Controllers.EstablishmentsController.GetMap(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Gov.Lclb.Cllb.Public.Controllers.EstablishmentsController.CreateEstablishment(Gov.Lclb.Cllb.Public.ViewModels.Establishment)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Gov.Lclb.Cllb.Public.Controllers.EstablishmentsController.UpdateEstablishment(Gov.Lclb.Cllb.Public.ViewModels.Establishment,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Gov.Lclb.Cllb.Public.Controllers.EstablishmentsController.UpdateEstablishment(Gov.Lclb.Cllb.Public.ViewModels.Establishment,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Gov.Lclb.Cllb.Public.Controllers.EstablishmentsController.DeleteEstablishment(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Gov.Lclb.Cllb.Public.Controllers.EstablishmentsController.DeleteEstablishment(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
