FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["carla-spice-sync-service/CarlaSpiceSync.csproj", "carla-spice-sync-service/"]
COPY ["cllc-interfaces/SharePoint/SharePoint.csproj", "cllc-interfaces/SharePoint/"]
COPY ["cllc-interfaces/SPICE/SpiceClient.csproj", "cllc-interfaces/SPICE/"]
COPY ["cllc-interfaces/Dynamics-Dataverse/Dynamics-Dataverse.csproj", "cllc-interfaces/Dynamics-Dataverse/"]

RUN dotnet restore "carla-spice-sync-service/CarlaSpiceSync.csproj"

COPY carla-spice-sync-service/ carla-spice-sync-service/
COPY cllc-interfaces/ cllc-interfaces/

WORKDIR "/src/carla-spice-sync-service"
RUN dotnet build "CarlaSpiceSync.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CarlaSpiceSync.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CarlaSpiceSync.dll"]
