apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cllc-web.fullname" . }}-nginx
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      root /usr/share/nginx/html;

      {{- $base := .Values.nginx.basePath | default "/lcrb" }}

      location {{ $base }}/ {
        try_files $uri $uri/ {{ $base }}/index.html;
      }

      {{- if .Values.nginx.cacheStatic }}
      location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri $uri/ {{ $base }}/index.html;
      }
      {{- end }}
    }
