FROM dotnet-22-rhel7:latest
# This image provides a .NET Core 2.0 environment you can use to run your .NET
# applications.

USER 0

# Install bzip

RUN pushd /opt \
    && yum install -y yum-utils \
	&& INSTALL_PKGS="bzip2" \
    && yum install -y $INSTALL_PKGS --enablerepo=rhel-7-server-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-dotnet-rpms \
    && rpm -V $INSTALL_PKGS \
    && yum clean all -y \
    && popd
	
USER 1001


