// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Lclb.Cllb.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of serviceappointment
    /// </summary>
    /// <remarks>
    /// Microsoft.Dynamics.CRM.serviceappointmentCollection
    /// </remarks>
    public partial class MicrosoftDynamicsCRMserviceappointmentCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMserviceappointmentCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMserviceappointmentCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMserviceappointmentCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMserviceappointmentCollection(IList<MicrosoftDynamicsCRMserviceappointment> value = default(IList<MicrosoftDynamicsCRMserviceappointment>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMserviceappointment> Value { get; set; }

    }
}
