// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Lclb.Cllb.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Microsoft.Dynamics.CRM.relationshipattribute
    /// </summary>
    public partial class MicrosoftDynamicsCRMrelationshipattribute
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMrelationshipattribute class.
        /// </summary>
        public MicrosoftDynamicsCRMrelationshipattribute()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMrelationshipattribute class.
        /// </summary>
        public MicrosoftDynamicsCRMrelationshipattribute(string componentidunique = default(string), string relationshipattributeid = default(string), string iscustomizable = default(string), System.DateTimeOffset? overwritetime = default(System.DateTimeOffset?), string _referencingattributeidValue = default(string), string solutionid = default(string), string _referencedattributeidValue = default(string), string _relationshipidValue = default(string), int? componentstate = default(int?), string name = default(string), bool? ismanaged = default(bool?), IList<MicrosoftDynamicsCRMsyncerror> relationshipattributeSyncErrors = default(IList<MicrosoftDynamicsCRMsyncerror>), IList<MicrosoftDynamicsCRMasyncoperation> relationshipattributeAsyncOperations = default(IList<MicrosoftDynamicsCRMasyncoperation>), IList<MicrosoftDynamicsCRMmailboxtrackingfolder> relationshipattributeMailboxTrackingFolders = default(IList<MicrosoftDynamicsCRMmailboxtrackingfolder>), IList<MicrosoftDynamicsCRMbulkdeletefailure> relationshipattributeBulkDeleteFailures = default(IList<MicrosoftDynamicsCRMbulkdeletefailure>), IList<MicrosoftDynamicsCRMprincipalobjectattributeaccess> relationshipattributePrincipalObjectAttributeAccesses = default(IList<MicrosoftDynamicsCRMprincipalobjectattributeaccess>), MicrosoftDynamicsCRMattribute referencingattributeidRelationshipattribute = default(MicrosoftDynamicsCRMattribute), MicrosoftDynamicsCRMattribute referencedattributeidRelationshipattribute = default(MicrosoftDynamicsCRMattribute), MicrosoftDynamicsCRMrelationship relationshipidRelationshipattribute = default(MicrosoftDynamicsCRMrelationship))
        {
            Componentidunique = componentidunique;
            Relationshipattributeid = relationshipattributeid;
            Iscustomizable = iscustomizable;
            Overwritetime = overwritetime;
            this._referencingattributeidValue = _referencingattributeidValue;
            Solutionid = solutionid;
            this._referencedattributeidValue = _referencedattributeidValue;
            this._relationshipidValue = _relationshipidValue;
            Componentstate = componentstate;
            Name = name;
            Ismanaged = ismanaged;
            RelationshipattributeSyncErrors = relationshipattributeSyncErrors;
            RelationshipattributeAsyncOperations = relationshipattributeAsyncOperations;
            RelationshipattributeMailboxTrackingFolders = relationshipattributeMailboxTrackingFolders;
            RelationshipattributeBulkDeleteFailures = relationshipattributeBulkDeleteFailures;
            RelationshipattributePrincipalObjectAttributeAccesses = relationshipattributePrincipalObjectAttributeAccesses;
            ReferencingattributeidRelationshipattribute = referencingattributeidRelationshipattribute;
            ReferencedattributeidRelationshipattribute = referencedattributeidRelationshipattribute;
            RelationshipidRelationshipattribute = relationshipidRelationshipattribute;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "componentidunique")]
        public string Componentidunique { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationshipattributeid")]
        public string Relationshipattributeid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iscustomizable")]
        public string Iscustomizable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overwritetime")]
        public System.DateTimeOffset? Overwritetime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_referencingattributeid_value")]
        public string _referencingattributeidValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "solutionid")]
        public string Solutionid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_referencedattributeid_value")]
        public string _referencedattributeidValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_relationshipid_value")]
        public string _relationshipidValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "componentstate")]
        public int? Componentstate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ismanaged")]
        public bool? Ismanaged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationshipattribute_SyncErrors")]
        public IList<MicrosoftDynamicsCRMsyncerror> RelationshipattributeSyncErrors { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationshipattribute_AsyncOperations")]
        public IList<MicrosoftDynamicsCRMasyncoperation> RelationshipattributeAsyncOperations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationshipattribute_MailboxTrackingFolders")]
        public IList<MicrosoftDynamicsCRMmailboxtrackingfolder> RelationshipattributeMailboxTrackingFolders { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationshipattribute_BulkDeleteFailures")]
        public IList<MicrosoftDynamicsCRMbulkdeletefailure> RelationshipattributeBulkDeleteFailures { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationshipattribute_PrincipalObjectAttributeAccesses")]
        public IList<MicrosoftDynamicsCRMprincipalobjectattributeaccess> RelationshipattributePrincipalObjectAttributeAccesses { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referencingattributeid_relationshipattribute")]
        public MicrosoftDynamicsCRMattribute ReferencingattributeidRelationshipattribute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referencedattributeid_relationshipattribute")]
        public MicrosoftDynamicsCRMattribute ReferencedattributeidRelationshipattribute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationshipid_relationshipattribute")]
        public MicrosoftDynamicsCRMrelationship RelationshipidRelationshipattribute { get; set; }

    }
}
