// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Lclb.Cllb.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// RetrieveDeprovisionedLanguagesResponse
    /// </summary>
    public partial class MicrosoftDynamicsCRMRetrieveDeprovisionedLanguagesResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMRetrieveDeprovisionedLanguagesResponse class.
        /// </summary>
        public MicrosoftDynamicsCRMRetrieveDeprovisionedLanguagesResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMRetrieveDeprovisionedLanguagesResponse class.
        /// </summary>
        public MicrosoftDynamicsCRMRetrieveDeprovisionedLanguagesResponse(IList<int?> retrieveDeprovisionedLanguages = default(IList<int?>))
        {
            RetrieveDeprovisionedLanguages = retrieveDeprovisionedLanguages;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RetrieveDeprovisionedLanguages")]
        public IList<int?> RetrieveDeprovisionedLanguages { get; set; }

    }
}
