// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Lclb.Cllb.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of adoxio_customautonumberrequest
    /// </summary>
    /// <remarks>
    /// Microsoft.Dynamics.CRM.adoxio_customautonumberrequestCollection
    /// </remarks>
    public partial class MicrosoftDynamicsCRMadoxioCustomautonumberrequestCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMadoxioCustomautonumberrequestCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMadoxioCustomautonumberrequestCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMadoxioCustomautonumberrequestCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMadoxioCustomautonumberrequestCollection(IList<MicrosoftDynamicsCRMadoxioCustomautonumberrequest> value = default(IList<MicrosoftDynamicsCRMadoxioCustomautonumberrequest>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMadoxioCustomautonumberrequest> Value { get; set; }

    }
}
