// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Lclb.Cllb.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MicrosoftDynamicsCRMteamroles
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftDynamicsCRMteamroles
        /// class.
        /// </summary>
        public MicrosoftDynamicsCRMteamroles()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftDynamicsCRMteamroles
        /// class.
        /// </summary>
        public MicrosoftDynamicsCRMteamroles(string versionnumber = default(string), string teamid = default(string), string teamroleid = default(string), string roleid = default(string))
        {
            Versionnumber = versionnumber;
            Teamid = teamid;
            Teamroleid = teamroleid;
            Roleid = roleid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "versionnumber")]
        public string Versionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "teamid")]
        public string Teamid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "teamroleid")]
        public string Teamroleid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roleid")]
        public string Roleid { get; set; }

    }
}
