FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["file-manager-service/file-manager-service.csproj", "file-manager-service/"]
COPY ["cllc-interfaces/SharePoint/SharePoint.csproj", "cllc-interfaces/SharePoint/"]

RUN dotnet restore "file-manager-service/file-manager-service.csproj"

COPY file-manager-service/ file-manager-service/
COPY cllc-interfaces/ cllc-interfaces/

WORKDIR "/src/file-manager-service"
RUN dotnet build "file-manager-service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "file-manager-service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "file-manager-service.dll"]
