<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>fe2fd249-51a1-4055-93ed-3f64fd3176a7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="openshift\**" />
    <Content Remove="openshift\**" />
    <EmbeddedResource Remove="openshift\**" />
    <None Remove="openshift\**" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\fileManager.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.1" />
    <PackageReference Include="Google.Protobuf" Version="3.27.2" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.63.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.Splunk" Version="3.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\cllc-interfaces\SharePoint\SharePoint.csproj" />
  </ItemGroup>

</Project>
