FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["federal-reporting-service/federal-reporting-service.csproj", "federal-reporting-service/"]
COPY ["cllc-interfaces/Dynamics-Dataverse/Dynamics-Dataverse.csproj", "cllc-interfaces/Dynamics-Dataverse/"]

RUN dotnet restore "federal-reporting-service/federal-reporting-service.csproj"

COPY federal-reporting-service/ federal-reporting-service/
COPY cllc-interfaces/ cllc-interfaces/
COPY file-manager-service/Protos/ file-manager-service/Protos/

WORKDIR "/src/federal-reporting-service"
RUN dotnet build "federal-reporting-service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "federal-reporting-service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "federal-reporting-service.dll"]
