FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["one-stop-service/one-stop-service.csproj", "one-stop-service/"]
COPY ["cllc-interfaces/OneStopRestClient/OneStopRestClient.csproj", "cllc-interfaces/OneStopRestClient/"]
COPY ["cllc-interfaces/Dynamics-Dataverse/Dynamics-Dataverse.csproj", "cllc-interfaces/Dynamics-Dataverse/"]

RUN dotnet restore "one-stop-service/one-stop-service.csproj"

COPY one-stop-service/ one-stop-service/
COPY cllc-interfaces/ cllc-interfaces/

WORKDIR "/src/one-stop-service"
RUN dotnet build "one-stop-service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "one-stop-service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "one-stop-service.dll"]
