<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <StartupObject>Gov.Jag.Lcrb.OneStopService.Program</StartupObject>
    <UserSecretsId>a8fa37fc-67d7-43f2-b3fe-d44dfeed50ee</UserSecretsId>
    <RootNamespace>Gov.Jag.Lcrb.OneStopService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="openshift\**" />
    <Content Remove="openshift\**" />
    <EmbeddedResource Remove="openshift\**" />
    <None Remove="openshift\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.1" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.18" />
    <PackageReference Include="Hangfire.Console" Version="1.4.2" />
    <PackageReference Include="Hangfire.MemoryStorage.Core" Version="1.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageReference Include="SoapCore" Version="1.1.0.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.Splunk" Version="3.7.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Unchase.Swashbuckle.AspNetCore.Extensions" Version="2.7.2" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\cllc-interfaces\OneStopRestClient\OneStopRestClient.csproj" />
    <ProjectReference Include="..\cllc-interfaces\Dynamics-Dataverse\Dynamics-Dataverse.csproj">
      <Aliases>DV</Aliases>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>

</Project>
