name: Backend Code Quality Check

on:
  pull_request:
    branches: [develop, LCSD-7876]
    paths:
      - "**/*.cs"
      - ".csharpierrc.yml"
      - ".csharpierignore"

jobs:
  csharpier-check:
    runs-on: ubuntu-latest
    name: Check C# Code Formatting

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Check C# formatting
        run: dotnet csharpier --check .

      - name: Comment on PR if formatting issues found
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Code formatting issues detected**\n\nPlease run `dotnet csharpier .` to fix formatting issues, then commit the changes.\n\nTo install the tool locally:\n```bash\ndotnet tool restore\ndotnet csharpier .\n```'
            })
