name: Backend Code Quality Check

on:
  pull_request:
    branches: [develop, LCSD-7876, LCSD-7876-2]
    paths:
      - "**/*.cs"
      - ".csharpierrc.yml"
      - ".csharpierignore"

jobs:
  csharpier-check:
    if: false
    runs-on: ubuntu-latest
    name: Check C# Code Formatting

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Check C# formatting
        id: csharpier
        run: dotnet csharpier --check .

      - name: Fail if quality checks failed
        if: steps.csharpier.outcome == 'failure'
        run: exit 1
