FROM openshift3/jenkins-slave-base-rhel7

# Labels consumed by Red Hat build service
LABEL com.redhat.component="rh-dotnet31-jenkins-slave-container" \
      name="dotnet/dotnet-31-jenkins-slave-rhel7" \
      version="3.1" \
      architecture="x86_64" \
      release="1" \
      io.k8s.display-name="Jenkins Slave .NET Core 3.1" \
      io.k8s.description="The jenkins slave dotnet image has the dotnet tools on top of the jenkins slave base image." \
      io.openshift.tags="openshift,jenkins,slave,dotnet,dotnet31"

# Don't download/extract docs for nuget packages
# Enable nodejs and dotnet scl
ENV DOTNET_CORE_VERSION=3.1 \
    TZ=GMT-7 \
    BASH_ENV=/usr/local/bin/scl_enable \
    ENV=/usr/local/bin/scl_enable \
    PROMPT_COMMAND=". /usr/local/bin/scl_enable" \
    ENABLED_COLLECTIONS="rh-nodejs10 rh-dotnet31" \
    NUGET_XMLDOC_MODE=skip

COPY contrib/bin/scl_enable /usr/local/bin/scl_enable

# Install
RUN INSTALL_PKGS="rh-dotnet31 rh-nodejs10-npm rh-nodejs10-nodejs-nodemon rh-dotnet31-dotnet-sdk-3.1 " && \
    yum install -y --setopt=tsflags=nodocs --disablerepo=\* \
      --enablerepo=rhel-7-server-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-dotnet-rpms,rhel-7-server-optional-rpms \
      $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all -y && \
# yum cache files may still exist (and quite large in size)
    rm -rf /var/cache/yum/*

# Trigger first time actions.
RUN scl enable rh-dotnet31 'dotnet help'

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

# may also need xorg-x11-server-Xvfb x11vnc

RUN yum -y install wget nano xorg-x11-xauth java-1.8.0-openjdk git rh-nodejs10-npm  && \   
	wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
	wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm && \
	yum -y localinstall epel-release-latest-7.noarch.rpm && \
	yum --enablerepo=rhel-7-server-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-dotnet-rpms,rhel-7-server-optional-rpms -y localinstall google-chrome-stable_current_x86_64.rpm && \
	rm google-chrome-stable_current_x86_64.rpm && \
	yum clean all -y && \
    rm -rf /var/cache/yum/* && \
    scl enable rh-nodejs10 bash

RUN echo ${PATH}

RUN ls /opt/rh/rh-nodejs10/root/usr/lib/

ENV PATH="/opt/rh/rh-nodejs10/root/usr/bin:/opt/app-root/node_modules/.bin:${PATH}"

RUN npm install -g @angular/cli && \
   npm install -g typescript

#	yum -y install firefox; yum clean all

# Add Chrome as a user
RUN groupadd -r chrome && useradd -r -g chrome -G audio,video chrome \
    && mkdir -p /home/chrome && chown -R chrome:chrome /home/chrome && \
    dbus-uuidgen > /var/lib/dbus/machine-id

ENV DOTNET_SSL_DIRS=/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

# Run Chrome non-privileged
USER chrome

CMD [ "/bin/bash" ]
